<div style="font-family: DejaVu Sans, sans-serif; padding: 20px;">
    <h2>EMPLOYEE LEDGER CONFIRMATION – FY {{ $employee->Year }}</h2>

    <p><strong>Employee Name:</strong> {{ $employee->full_name }}</p>
    <p><strong>Employee Code:</strong> {{ $employee->EmpCode }}</p>
    <p><strong>Department:</strong> {{ $employee->department_name }}</p>
    <p><strong>Ledger Period:</strong> 01-Apr-2024 to 31-Mar-2025</p>
    <p><strong>Confirmation Date:</strong> {{ $employee->confirmed_at }}</p>

    <h3>Declaration:</h3>
    <p>I, {{ $employee->full_name }}, have reviewed the attached ledger and confirm that it reflects the correct record of my payroll, claims, advances, and settlements. I confirm the same electronically via the ESS portal.</p>

    <p><strong>Confirmed electronically</strong></p>
    <p><strong>IP Address/Device:</strong> {{ $employee->ip_address }}</p>

    <p><small>Generated by Peepal on {{ $employee->generated_at }}</small></p>
    <p><small><em>This document is system-generated and does not require a physical signature.</em></small></p>
</div>
