<!DOCTYPE html>
<html>
<head>
    <title>Ledger + Confirmation</title>
    <style>
        body { font-family: sans-serif; padding: 20px; }
        .section { margin: 30px 0; }
        .label { font-weight: bold; }
        .declaration { font-size: 14px; }
    </style>
</head>
<body>

    @if($employee->ledger_path)
        <!-- ✅ Show the PDF first -->
        <div class="section">
            <embed src="{{ $employee->ledger_path }}" type="application/pdf" width="100%" height="800px" />
        </div>
    @else
        <div class="alert alert-danger">Ledger PDF not found.</div>
    @endif

    <!-- ✅ Declaration Section Below -->
    <div class="section">
        <h3>EMPLOYEE LEDGER CONFIRMATION – FY {{ $employee->Year }}</h3>

        <p><span class="label">Employee Name:</span> {{ $employee->full_name }}</p>
        <p><span class="label">Employee Code:</span> {{ $employee->EmpCode }}</p>
        <p><span class="label">Department:</span> {{ $employee->department_name }}</p>
        <p><span class="label">Ledger Period:</span> 01-Apr-2024 to 31-Mar-2025</p>
        <p><span class="label">Confirmation Date:</span> {{ $employee->confirmed_at }}</p>

        <div class="declaration mt-4">
            <p><strong>Declaration:</strong></p>
            <p>I, {{ $employee->full_name }}, have reviewed the attached ledger and confirm that it reflects the correct record of my payroll, claims, advances, and settlements. I confirm the same electronically via the ESS portal.</p>

            <p>☑️ Confirmed electronically</p>
            <p><b>IP Address/Device:</b> {{ $employee->ip_address }}</p>

            <p class="mt-4"><small>Generated by ESS on {{ $employee->generated_at }}</small><br>
            <em>*This document is system-generated and does not require a physical signature.*</em></p>
        </div>
    </div>

    <!-- Optional Print Button -->
    <div class="text-center mt-4">
        <button onclick="window.print()" class="btn btn-primary">🖨️ Print Confirmation</button>
    </div>

</body>
</html>
